#!/usr/bin/env python

import os
import json
import pickle
import sys
import traceback
import pandas as pd
import lightgbm as lgb
import numpy as np
from sklearn.metrics import mean_squared_error


# These are the paths to where SageMaker mounts interesting things in your container.

prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')
param_path = os.path.join(prefix, 'input/config/hyperparameters.json')

# This algorithm has a single channel of input data called 'training'. Since we run in
# File mode, the input files are copied to the directory specified here.

channel_name='training'
training_path = os.path.join(input_path, channel_name)
channel_name_valid='validating'
testing_path = os.path.join(input_path, channel_name_valid)


# The function to execute the training.
def train():
    print('Starting the training.')
    try:
        # Read in any hyperparameters that the user passed with the training job
        with open(param_path, 'r') as tc:
            trainingParams = json.load(tc)

        print(trainingParams)
        input_files = [ os.path.join(training_path, file) for file in os.listdir(training_path) ]
        valid_files = [ os.path.join(testing_path, file) for file in os.listdir(testing_path) ]
        if (len(input_files) == 0) | (len(valid_files) == 0):
            raise ValueError(('There are no files in {}.\n' +
                              'This usually indicates that the channel ({}) was incorrectly specified,\n' +
                              'the data specification in S3 was incorrectly specified or the role specified\n' +
                              'does not have permission to access the data.').format(training_path, channel_name))
        elif (len(input_files) == 1) & (len(valid_files) == 1):
            df_train = pd.read_csv(input_files[0])
            df_valid = pd.read_csv(valid_files[0])
        X = df_train.iloc[:,1:]
        Xval = df_valid.iloc[:,1:]
        y = df_train.iloc[:,0]
        yval = df_valid.iloc[:,0]
        print(len(X), len(y))
        print(len(Xval), len(yval))
        print("csv parsed")

        cat_features = [2,3,4]
        lgb_train = lgb.Dataset(X.values, y.values,categorical_feature=cat_features)
        lgb_eval = lgb.Dataset(Xval.values, yval.values,categorical_feature=cat_features, reference=lgb_train)
        gbm = lgb.train(trainingParams,
                        lgb_train,
                        num_boost_round=10000,
                        categorical_feature=cat_features,
                        valid_sets=[lgb_train, lgb_eval],
                        callbacks=[lgb.early_stopping(stopping_rounds=50)])
        
        ypred = gbm.predict(Xval, num_iteration=gbm.best_iteration)
        print('rootmse:', mean_squared_error(yval, ypred, squared=False))
        filename = os.path.join(model_path, 'lgb_model.pkl')
        pickle.dump(gbm, open(filename, 'wb'))
        print('Training complete.')
        
    except Exception as e:
        # Write out an error file. This will be returned as the failureReason in the
        # DescribeTrainingJob result.
        trc = traceback.format_exc()
        with open(os.path.join(output_path, 'failure'), 'w') as s:
            s.write('Exception during training: ' + str(e) + '\n' + trc)
        # Printing this causes the exception to be in the training job logs, as well.
        print('Exception during training: ' + str(e) + '\n' + trc, file=sys.stderr)
        # A non-zero exit code causes the training job to be marked as Failed.
        sys.exit(255)

if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)